apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversor
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conversor
  template:
    metadata:
      labels:
        app: conversor
    spec:
      containers:
      - name: conversor
        image: thiagoduran/conversor-complete-devops:latest
        ports:
        - containerPort: 8000
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: DATABASE_URL