apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversor-deployment
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: conversor
  template:
    metadata:
      labels:
        app: conversor
    spec:
      containers:
        - name: conversor
          image: thiagoduran/conversor-complete-devops:latest
          ports:
            - containerPort: 8000
