apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversor-deploy
  labels:
    app: conversor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conversor
  template:
    metadata:
      labels:
        app: conversor
    spec:
      containers:
      - name: conversor-container
        image: thiagoduran/conversor-complete-devops:latest
        ports:
        - containerPort: 8000
        env:
        - name: ENV
          value: "staging"
        # Optional: health checks
        readinessProbe:
          httpGet:
            path: /docs
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10
