apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversor-deployment
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: conversor
  template:
    metadata:
      labels:
        app: conversor
    spec:
      containers:
        - name: conversor
          image: thiagoduran/conversor-complete-devops:latest
          ports:
            - containerPort: 8000
