apiVersion: v1
kind: Service
metadata:
  name: conversor-service
spec:
  selector:
    app: conversor
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80   
      targetPort: 8000