apiVersion: v1
kind: Service
metadata:
  name: conversor-service
  namespace: staging
  labels:
    app: conversor
    prometheus.io/scrape: "true"
    prometheus.io/port: "8000"
spec:
  selector:
    app: conversor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
