apiVersion: v1
kind: Service
metadata:
  name: conversor-service
  namespace: production
spec:
  selector:
    app: conversor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
