name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Code checkout
      uses: actions/checkout@v3

    - name: Configure Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: PYTHONPATH=. pytest

    # Login Docker Hub
    - name: Login Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Docker image build
    - name: Docker image build
      run: |
        docker build -t thiagoduran/conversor-complete-devops:latest .

    # Push to Docker Hub
    - name: Docker Hub Push
      run: |
        docker push thiagoduran/conversor-complete-devops:latest


  staging-deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'
    
    - name: Authenticate cluster (staging)
      run: |
        echo "${{ secrets.CLUSTER_KUBECONFIG }}" | base64 --decode > kubeconfig
        export KUBECONFIG=$(pwd)/kubeconfig
        kubectl get nodes
    
    - name: Deploy to Staging
      run: |
        echo "${{ secrets.CLUSTER_KUBECONFIG }}" | base64 --decode > kubeconfig
        export KUBECONFIG=$(pwd)/kubeconfig
        kubectl apply --validate=false -f k8s/deployment-staging.yaml
        kubectl apply --validate=false -f k8s/service-staging.yaml

  production-deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    environment:
      name: production
      url: 45.55.96.177
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Authenticate cluster and deploy (production)
      run: |
        echo "${{ secrets.CLUSTER_KUBECONFIG }}" | base64 --decode > kubeconfig
        export KUBECONFIG=$(pwd)/kubeconfig

        kubectl get nodes
    
        kubectl apply --validate=false -f k8s/deployment-production.yaml
        kubectl apply --validate=false -f k8s/service-production.yaml